import RecipientEventProcessors from './RecipientEventProcessors';

module.exports.recipientImportedProcessor = RecipientEventProcessors.recipientImportedProcessor;
module.exports.recipientCreatedProcessor = RecipientEventProcessors.recipientCreatedProcessor;
module.exports.recipientUpdatedProcessor = RecipientEventProcessors.recipientUpdatedProcessor;
module.exports.recipientDeletedProcessor = RecipientEventProcessors.recipientDeletedProcessor;
